### ISSUE TITLE
Rethink if all fields should be nullable

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/graphql#351]
Currently, all fields are required to be nullable.

But I believe it doesn't make much sense in specific cases. For example, take into account boolean fields:

```
customerSupport {
  hasGuaranteeChat
}
```

The return value should be always true/false. `null` probably means there is an error in resolver.

**Comment by VaclavSir** [comment]
One reason for nullable fields is to limit effects of errors in resolvers. If there is an error in one field, at least some other fields can be delivered.

In this case I think it would be better to check the value in the resolver. Something like this:

```
({ hasGuaranteeChat }) => typeof hasGuaranteeChat === 'boolean'
  ? hasGuaranteeChat
  : new Error('Failed to fetch hasGuaranteeChat')
```

That way we don't throw away the whole object and we get the error reported (eg. when the underlying backend stops delivering the field).

**Comment by michalsanger** [comment]
@VaclavSir you mean?
```js
throw new Error('Failed to fetch hasGuaranteeChat'
```

**Comment by jaroslav-kubicek** [comment]
> Other option would be to disallow null for this field which effectively means that you have to nuke the whole CS object in case of the error in one particular resolver.

yes, thanks, I'm trying to think of best practices and thought that maybe boolean fields should always return value or explode. Also, it might be true I came to this conclusion because this particular field is crucial for our client, but it might be less important for someone else.

**Comment by mrtnzlml** [comment]
@jaroslav-kubicek 

> I thought that maybe boolean fields should always return value or explode

I agree with that. We consider `null` to be this "exploded" version because the idea is not to destroy the whole object by default. But feel free to do it if it makes sense. We are already doing it with opaque `id` fields because it's too dangerous to assume that object with broken ID is fine. All these IDs are always defined as `ID!`. I will send you an example from the Portalo project where we actually explode the whole object in case of invalid `id` values (this project is too benevolent).

Just remember that you are not going to be the only user of this API so it's wrong to make assumptions only for your application.

**Comment by VaclavSir** [comment]
@michalsanger
I prefer returning errors in GraphQL resolving instead of throwing them, although in a leaf resolver it has the same effect (the value resolves as `null` and the error is added to the errors list).

If the code was in the leaf resolver, then throwing would be an option (not preferred by me), but if it was inside a function that returns the whole object (like all these `ApiSanitizer.js` in this repo), then throwing the error destroys the whole object. And if it was called from a Dataloader's batch function, then it would destroy the whole batch, even if there was a problem only on one field of one batch item.

**Comment by mrtnzlml** [comment]
I believe this is answered now.
