### ISSUE TITLE
Use custom connectionFromArray everywhere

### ISSUE THREAD

**Issue by michalsanger** [kiwicom/graphql#53]
> Could you please use [this Eslint rule](https://eslint.org/docs/rules/no-restricted-imports) to make sure we'll use it everywhere even in the future? See for example this: https://github.com/kiwicom/react-native-app/blob/e39ea6a773dfffc14180edce4cfb7e1caa4b0b71/.eslintrc.js#L40-L74

**Comment by Rulsky** [comment]
Hello, @michalsanger, thank you for your presentation yesterday. Can I take it as my first PR?

**Comment by Rulsky** [comment]
So, in order to make this rule work, I had to upgrade eslint to v4.19.1 and babel-eslint to v8.2.2,
because current version of eslint has a bug specificly related to this rule in part of parsing `importNames` property of the rule.

After running linting upon whole `src` dir it revealed several places where native `connectionFromArray` from `graphql-relay` is used. They are:
````bash
src/FAQ/queries/AllFAQCategories.js

src/FAQ/queries/AllFAQs.js

src/flight/queries/AllFlights.js

src/hotel/queries/AllAvailableHotels.js

src/hotel/types/outputs/Hotel.js

src/hotel/types/outputs/HotelRoom.js

src/location/queries/AllSubLocations.js
````

**Comment by mrtnzlml** [comment]
@Rulsky Can you try to prepare the PR? Upgrades of eslint and babel-eslint dependencies are fine... 🙂

**Comment by Rulsky** [comment]
Hello, @mrtnzlml, I have created PR, take a look at #72.
